version: '3.8'

services:
  php:
    build: ./php
    container_name: login_crypto_php
    volumes:
      - ./php/src:/var/www/html
      - ./frontend:/var/www/html/frontend
    networks:
      - app-network
    depends_on:
      - db

  apache:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    container_name: login_crypto_apache
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./php/src:/var/www/html
      - ./frontend:/var/www/html/frontend
      - ./apache/apache-config:/etc/apache2-config
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: postgres:13
    container_name: login_crypto_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: excel_test_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
