version: '3.8'

services:
  php:
    build: ./php
    container_name: login_crypto_php
    volumes:
      - ./php/src:/var/www/html
      - ./frontend:/var/www/html/frontend 
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: login_crypto_nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/src:/var/www/html
      - ./frontend:/var/www/html/frontend
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: postgres:13
    container_name: login_crypto_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
